name: publish-npm-sdk-latest

on:
  push:
    tags:
      - 'web3telegram-v*'

jobs:
  publish-npm:
    uses: ./.github/workflows/reusable-sdk-npm.yml
    with:
      tag: 'latest'
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
