name: Test Organization Secrets Access

on:
  push:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test SCONTAIN_REGISTRY_USERNAME Secret
        run: |
          echo "Testing SCONTAIN_REGISTRY_USERNAME secret access..."
          if [ -n "${{ secrets.SCONTAIN_REGISTRY_USERNAME }}" ]; then
            echo "✅ SCONTAIN_REGISTRY_USERNAME is accessible"
            echo "Length: ${#SCONTAIN_REGISTRY_USERNAME}"
          else
            echo "❌ SCONTAIN_REGISTRY_USERNAME is NOT accessible"
          fi

      - name: Test SCONTAIN_REGISTRY_PAT Secret
        run: |
          echo "Testing SCONTAIN_REGISTRY_PAT secret access..."
          if [ -n "${{ secrets.SCONTAIN_REGISTRY_PAT }}" ]; then
            echo "✅ SCONTAIN_REGISTRY_PAT is accessible"
            echo "Length: ${#SCONTAIN_REGISTRY_PAT}"
          else
            echo "❌ SCONTAIN_REGISTRY_PAT is NOT accessible"
          fi

      - name: Test DOCKERHUB_PAT Secret
        run: |
          echo "Testing DOCKERHUB_PAT secret access..."
          if [ -n "${{ secrets.DOCKERHUB_PAT }}" ]; then
            echo "✅ DOCKERHUB_PAT is accessible"
            echo "Length: ${#DOCKERHUB_PAT}"
          else
            echo "❌ DOCKERHUB_PAT is NOT accessible"
          fi

      - name: Test SCONIFY_SIGNING_PRIVATE_KEY Secret
        run: |
          echo "Testing SCONIFY_SIGNING_PRIVATE_KEY secret access..."
          if [ -n "${{ secrets.SCONIFY_SIGNING_PRIVATE_KEY }}" ]; then
            echo "✅ SCONIFY_SIGNING_PRIVATE_KEY is accessible"
            echo "Length: ${#SCONIFY_SIGNING_PRIVATE_KEY}"
          else
            echo "❌ SCONIFY_SIGNING_PRIVATE_KEY is NOT accessible"
          fi

      - name: Test DOCKERHUB_USERNAME Variable
        run: |
          echo "Testing DOCKERHUB_USERNAME variable access..."
          if [ -n "${{ vars.DOCKERHUB_USERNAME }}" ]; then
            echo "✅ DOCKERHUB_USERNAME is accessible"
            echo "Value: ${{ vars.DOCKERHUB_USERNAME }}"
          else
            echo "❌ DOCKERHUB_USERNAME is NOT accessible"
          fi

      - name: Test Deployment Secrets
        run: |
          echo "Testing deployment-related secrets..."

          # Test wallet secrets
          if [ -n "${{ secrets.WEB3TELEGRAM_DAPP_OWNER_DEV_PRIVATEKEY }}" ]; then
            echo "✅ WEB3TELEGRAM_DAPP_OWNER_DEV_PRIVATEKEY is accessible"
          else
            echo "❌ WEB3TELEGRAM_DAPP_OWNER_DEV_PRIVATEKEY is NOT accessible"
          fi

          if [ -n "${{ secrets.WEB3TELEGRAM_DAPP_OWNER_PROD_PRIVATEKEY }}" ]; then
            echo "✅ WEB3TELEGRAM_DAPP_OWNER_PROD_PRIVATEKEY is accessible"
          else
            echo "❌ WEB3TELEGRAM_DAPP_OWNER_PROD_PRIVATEKEY is NOT accessible"
          fi

          # Test deployer secrets
          if [ -n "${{ secrets.DEPLOYER_DEV_PRIVATEKEY }}" ]; then
            echo "✅ DEPLOYER_DEV_PRIVATEKEY is accessible"
          else
            echo "❌ DEPLOYER_DEV_PRIVATEKEY is NOT accessible"
          fi

          if [ -n "${{ secrets.DEPLOYER_PROD_PRIVATEKEY }}" ]; then
            echo "✅ DEPLOYER_PROD_PRIVATEKEY is accessible"
          else
            echo "❌ DEPLOYER_PROD_PRIVATEKEY is NOT accessible"
          fi

          # Test Telegram secrets
          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}" ]; then
            echo "✅ TELEGRAM_BOT_TOKEN_DEV is accessible"
          else
            echo "❌ TELEGRAM_BOT_TOKEN_DEV is NOT accessible"
          fi

          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN_PROD }}" ]; then
            echo "✅ TELEGRAM_BOT_TOKEN_PROD is accessible"
          else
            echo "❌ TELEGRAM_BOT_TOKEN_PROD is NOT accessible"
          fi

          # Test whitelist addresses
          if [ -n "${{ secrets.WEB3TELEGRAM_WHITELIST_DEV_ADDRESS }}" ]; then
            echo "✅ WEB3TELEGRAM_WHITELIST_DEV_ADDRESS is accessible"
          else
            echo "❌ WEB3TELEGRAM_WHITELIST_DEV_ADDRESS is NOT accessible"
          fi

          if [ -n "${{ secrets.WEB3TELEGRAM_WHITELIST_PROD_ADDRESS }}" ]; then
            echo "✅ WEB3TELEGRAM_WHITELIST_PROD_ADDRESS is accessible"
          else
            echo "❌ WEB3TELEGRAM_WHITELIST_PROD_ADDRESS is NOT accessible"
          fi

      - name: Summary
        run: |
          echo "## Secret Access Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This workflow tests access to organization secrets and variables." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note**: This is a debugging workflow to verify secret access." >> $GITHUB_STEP_SUMMARY
          echo "Remove this workflow once the issue is resolved." >> $GITHUB_STEP_SUMMARY
